apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubefed-controller-manager
  labels:
    kubefed-control-plane: controller-manager
{{- if .Values.controller.annotations }}
  annotations:
{{ toYaml .Values.controller.annotations | indent 4 }}
{{- end }}
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      kubefed-control-plane: controller-manager
  strategy: {}
  template:
    metadata:
      labels:
        kubefed-control-plane: controller-manager
      {{- if .Values.controller.forceRedeployment }}
      annotations:
        rollme: {{ randAlphaNum 5 | quote }}
      {{- end }}
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml .Values.imagePullSecrets | indent 8 }}
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.commonNodeSelector | nindent 8 }}
      tolerations:
        {{- toYaml .Values.commonTolerations | nindent 8 }}
      securityContext:
        runAsUser: 1001
      serviceAccountName: kubefed-controller
      containers:
      - args:
        - --leader-elect
        - --clustername={{ .Values.config.cluster }}
        - --namespace={{ .Values.config.namespace }}
        - --max-concurrent-reconciles={{ .Values.config.maxConcurrentReconciles }}
        image: "{{ .Values.controller.repository }}/{{ .Values.controller.image }}:{{ .Values.controller.tag }}"
        imagePullPolicy: "{{ .Values.controller.imagePullPolicy }}"
        name: controller-manager
{{- if .Values.controller.env }}
        env:
{{- range $key, $value := .Values.controller.env }}
        - name: "{{ $key }}"
          value: "{{ $value }}"
{{- end }}
{{- end }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 20
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
{{- if .Values.controller.resources }}
{{ toYaml .Values.controller.resources | indent 12 }}
{{- end }}
      terminationGracePeriodSeconds: 10
