# permissions for end users to view kubefedclusters.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubefedcluster-viewer-role
rules:
- apiGroups:
  - core.kubefed.io
  resources:
  - kubefedclusters
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.kubefed.io
  resources:
  - kubefedclusters/status
  verbs:
  - get
