
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - core.kubefed.io
  resources:
  - kubefedclusters
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.kubefed.io
  resources:
  - kubefedclusters/finalizers
  verbs:
  - update
- apiGroups:
  - core.kubefed.io
  resources:
  - kubefedclusters/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - types.kubefed.io
  resources:
  - federatedobjects
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - types.kubefed.io
  resources:
  - federatedobjects/finalizers
  verbs:
  - update
- apiGroups:
  - types.kubefed.io
  resources:
  - federatedobjects/status
  verbs:
  - get
  - patch
  - update
